services:
  - type: web
    name: telegram-cinema-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TOKEN
        fromService:
          type: web
          name: telegram-cinema-bot
          envVarKey: TOKEN
